const fs = require('fs');
const file = '/home/ubuntu/apps/beratnyaCrown/src/app/dashboard/athletes/page.tsx';
let content = fs.readFileSync(file, 'utf8');

// Bersihkan tag tab yang diletakkan sembarangan oleh skrip patch awal saya tadi
content = content.replace(
  '<Tabs defaultValue="users" className="w-full">\\n<TabsList className="bg-black/40 border border-white/10 mb-4">\\n<TabsTrigger value="users" className="data-[state=active]:bg-rose-500/20 data-[state=active]:text-rose-300">Pengguna App (Akun)</TabsTrigger>\\n<TabsTrigger value="athletes" className="data-[state=active]:bg-cyan-500/20 data-[state=active]:text-cyan-300">Daftar Atlit (Latihan)</TabsTrigger>\\n</TabsList>\\n\\n<TabsContent value="users">\\n<Card className="border-rose-500/20 bg-rose-950/10 backdrop-blur-md shadow-xl text-slate-100">',
  '<Tabs defaultValue="users" className="w-full">\n<TabsList className="bg-black/40 border border-white/10 mb-4">\n<TabsTrigger value="users" className="data-[state=active]:bg-rose-500/20 data-[state=active]:text-rose-300">Pengguna App (Akun)</TabsTrigger>\n<TabsTrigger value="athletes" className="data-[state=active]:bg-cyan-500/20 data-[state=active]:text-cyan-300">Daftar Atlit (Latihan)</TabsTrigger>\n</TabsList>\n\n<TabsContent value="users">\n<Card className="border-rose-500/20 bg-rose-950/10 backdrop-blur-md shadow-xl text-slate-100">'
);

content = content.replace(
  '</Table>\\n            </div>\\n          </CardContent>\\n        </Card>\\n</TabsContent>\\n\\n<TabsContent value="athletes">\\n  <Card className="border-cyan-500/20 bg-cyan-950/10 backdrop-blur-md shadow-xl text-slate-100">\\n    <CardHeader className="pb-3 border-b border-white/5">\\n      <div className="flex items-center justify-between">\\n        <div>\\n          <CardTitle className="text-lg text-cyan-100 flex items-center gap-2">\\n            <UserPlus className="h-5 w-5 text-cyan-400" />\\n            Daftar Atlit Latihan\\n          </CardTitle>\\n          <CardDescription className="text-cyan-200/60 mt-1">\\n            Nama di sini akan muncul di formulir absensi latihan kalender.\\n          </CardDescription>\\n        </div>\\n        <Badge className="bg-cyan-500/20 text-cyan-300 border border-cyan-500/30">\\n          {crownAthletes.length} Atlit\\n        </Badge>\\n      </div>\\n    </CardHeader>\\n    <CardContent className="pt-4 space-y-4">\\n      <div className="flex gap-2">\\n        <Input \\n          placeholder="Nama Atlit Baru..." \\n          value={newAthleteName} \\n          onChange={(e) => setNewAthleteName(e.target.value)}\\n          className="bg-black/50 border-white/10 text-white max-w-sm"\\n        />\\n        <Button onClick={handleAddAthlete} className="bg-cyan-600 hover:bg-cyan-500 text-white">Tambah</Button>\\n      </div>\\n      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">\\n        {crownAthletes.sort((a,b) => a.name.localeCompare(b.name)).map(ath => (\\n          <div key={ath.id} className="flex items-center justify-between bg-black/40 border border-white/10 p-3 rounded-lg">\\n            <span className="text-sm text-slate-200">{ath.name}</span>\\n            <button onClick={() => handleDeleteAthlete(ath.id)} className="text-red-400 hover:text-red-300 hover:bg-red-500/10 p-1.5 rounded transition">\\n              <Trash2 className="h-4 w-4" />\\n            </button>\\n          </div>\\n        ))}\\n      </div>\\n    </CardContent>\\n  </Card>\\n</TabsContent>\\n</Tabs>',
  '</Table>\n            </div>\n          </CardContent>\n        </Card>\n</TabsContent>\n\n<TabsContent value="athletes">\n  <Card className="border-cyan-500/20 bg-cyan-950/10 backdrop-blur-md shadow-xl text-slate-100">\n    <CardHeader className="pb-3 border-b border-white/5">\n      <div className="flex items-center justify-between">\n        <div>\n          <CardTitle className="text-lg text-cyan-100 flex items-center gap-2">\n            <UserPlus className="h-5 w-5 text-cyan-400" />\n            Daftar Atlit Latihan\n          </CardTitle>\n          <CardDescription className="text-cyan-200/60 mt-1">\n            Nama di sini akan muncul di formulir absensi latihan kalender.\n          </CardDescription>\n        </div>\n        <Badge className="bg-cyan-500/20 text-cyan-300 border border-cyan-500/30">\n          {crownAthletes.length} Atlit\n        </Badge>\n      </div>\n    </CardHeader>\n    <CardContent className="pt-4 space-y-4">\n      <div className="flex gap-2">\n        <Input \n          placeholder="Nama Atlit Baru..." \n          value={newAthleteName} \n          onChange={(e) => setNewAthleteName(e.target.value)}\n          className="bg-black/50 border-white/10 text-white max-w-sm"\n        />\n        <Button onClick={handleAddAthlete} className="bg-cyan-600 hover:bg-cyan-500 text-white">Tambah</Button>\n      </div>\n      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">\n        {crownAthletes.sort((a,b) => a.name.localeCompare(b.name)).map(ath => (\n          <div key={ath.id} className="flex items-center justify-between bg-black/40 border border-white/10 p-3 rounded-lg">\n            <span className="text-sm text-slate-200">{ath.name}</span>\n            <button onClick={() => handleDeleteAthlete(ath.id)} className="text-red-400 hover:text-red-300 hover:bg-red-500/10 p-1.5 rounded transition">\n              <Trash2 className="h-4 w-4" />\n            </button>\n          </div>\n        ))}\n      </div>\n    </CardContent>\n  </Card>\n</TabsContent>\n</Tabs>'
);

// Ada literal string escaped yang bocor di DOM React, betulkan
content = content.replace(/\\n/g, '\n');

fs.writeFileSync(file, content);
console.log('Fixed escaped newlines');
